DEBUG 2022-07-06 11:40:04.911 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-07-06 11:40:04.911 UTC: 	 Running on: Linux lxplus716.cern.ch 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-07-06 11:40:04.912 UTC: 	 Executing command: 'submit'
DEBUG 2022-07-06 11:40:04.922 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dvats/.crab3
INFO 2022-07-06 11:40:04.949 UTC: 	 Will use CRAB configuration file crab_17F.py
DEBUG 2022-07-06 11:40:04.949 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-07-06 11:40:05.148 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-07-06 11:40:05.149 UTC: 	 Working area '/afs/cern.ch/user/d/dvats/public/for_res_studies/CMSSW_10_2_22/src/edanalyzer_for_resolution/edanalyzer/python/crab_jmeTriggerNTuple_SingleMuon_17F' already exists 
Please change the requestName in the config file
ERROR 2022-07-06 11:40:05.149 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/d/dvats/public/for_res_studies/CMSSW_10_2_22/src/edanalyzer_for_resolution/edanalyzer/python/crab_jmeTriggerNTuple_SingleMuon_17F' already exists 
Please change the requestName in the config file
INFO 2022-07-06 11:40:05.175 UTC: 	 Log file is /afs/cern.ch/user/d/dvats/public/for_res_studies/CMSSW_10_2_22/src/edanalyzer_for_resolution/edanalyzer/python/crab.log
DEBUG 2022-07-06 12:01:08.763 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-07-06 12:01:08.763 UTC: 	 Running on: Linux lxplus754.cern.ch 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-07-06 12:01:08.763 UTC: 	 Executing command: 'submit'
DEBUG 2022-07-06 12:01:08.763 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dvats/.crab3
INFO 2022-07-06 12:01:08.764 UTC: 	 Will use CRAB configuration file crab_16H.py
DEBUG 2022-07-06 12:01:08.764 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-07-06 12:01:08.858 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-07-06 12:01:08.858 UTC: 	 Working area '/afs/cern.ch/user/d/dvats/public/for_res_studies/CMSSW_10_2_22/src/edanalyzer_for_resolution/edanalyzer/python/crab_jmeTriggerNTuple_SingleMuon_16H' already exists 
Please change the requestName in the config file
ERROR 2022-07-06 12:01:08.858 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/d/dvats/public/for_res_studies/CMSSW_10_2_22/src/edanalyzer_for_resolution/edanalyzer/python/crab_jmeTriggerNTuple_SingleMuon_16H' already exists 
Please change the requestName in the config file
INFO 2022-07-06 12:01:08.924 UTC: 	 Log file is /afs/cern.ch/user/d/dvats/public/for_res_studies/CMSSW_10_2_22/src/edanalyzer_for_resolution/edanalyzer/python/crab.log
